import Link from 'next/link';
import { ArrowRight, FileText, Flame, Ruler, Sparkles, Truck, Utensils, Warehouse, WashingMachine } from 'lucide-react';
import { Header } from './Header';
import { Footer } from './Footer';

const CATALOG_PDF_URL = 'https://drive.google.com/file/d/1z7AQFK96ZgiyVbYAklXcaeULMK_zhbTS/view?usp=drivesdk';
const WHATSAPP_URL = 'https://wa.me/6285122001051?text=Halo%20Tim%20BBKitchen%2C%20saya%20ingin%20konsultasi%20kebutuhan%20peralatan%20Dapur%20MBG.';
const BGN_JUKNIS_URL = 'https://bgn.go.id/juknis';

const equipmentGroups = [
  { title: 'Preparation Equipment', description: 'Meja kerja stainless, meja preparation, sink dan rak.', icon: Ruler },
  { title: 'Cooking Equipment', description: 'Kwali range, stockpot, rice steamer dan peralatan memasak skala besar.', icon: Flame },
  { title: 'Washing Equipment', description: 'Single sink, double sink, sink jumbo dan kebutuhan pencucian.', icon: WashingMachine },
  { title: 'Storage Equipment', description: 'Rack, showcase, chiller dan freezer.', icon: Warehouse },
  { title: 'Packing & Distribution', description: 'Food trolley dan equipment pendukung pemorsian/pengemasan.', icon: Truck },
  { title: 'Exhaust & Installation', description: 'Hood, blower, ducting dan kebutuhan instalasi.', icon: Sparkles },
];

export function DapurMbgLanding() {
  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 font-sans">
      <Header />
      <main>
        <section className="relative overflow-hidden bg-slate-950 text-white">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(16,185,129,0.18),transparent_35%),radial-gradient(circle_at_15%_80%,rgba(245,158,11,0.12),transparent_30%)]" />
          <div className="relative max-w-7xl mx-auto px-4 py-16 sm:py-20 lg:py-24"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-emerald-400">BBKitchen • Dapur MBG</p><h1 className="mt-4 text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.02]">Peralatan Dapur MBG &amp; Equipment SPPG</h1><p className="mt-6 max-w-2xl text-sm sm:text-base leading-7 text-slate-300">Solusi peralatan dapur komersial untuk kebutuhan preparation, cooking, washing, storage, packing, dan exhaust pada operasional Dapur MBG/SPPG.</p><div className="mt-8 flex flex-col sm:flex-row gap-3"><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-500 px-5 py-3 text-sm font-black text-white hover:bg-emerald-400 transition-colors">Konsultasi Kebutuhan Dapur <ArrowRight className="w-4 h-4" /></a><Link href="#equipment" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-white/5 px-5 py-3 text-sm font-bold text-slate-200 hover:bg-white/10 transition-colors">Lihat Equipment</Link></div></div></div>
        </section>
        <section id="equipment" className="max-w-7xl mx-auto px-4 py-12 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Peralatan Dapur MBG</p><h2 className="mt-2 text-2xl sm:text-3xl font-black tracking-tight">Peralatan Dapur MBG</h2><p className="mt-3 text-sm leading-6 text-slate-600">BBKitchen menyediakan berbagai equipment untuk kebutuhan area kerja dapur MBG dan SPPG.</p></div><div className="mt-8 grid grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-5">{equipmentGroups.map(({ title, description, icon: Icon }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="w-5 h-5" /></div><h3 className="mt-4 text-sm sm:text-base font-black">{title}</h3><p className="mt-1.5 text-xs sm:text-sm leading-5 text-slate-500">{description}</p></article>)}</div></section>
        <section className="bg-white border-y border-slate-200"><div className="max-w-7xl mx-auto px-4 py-12 sm:py-16 grid lg:grid-cols-[1.15fr_0.85fr] gap-8 items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Layout Dapur MBG / SPPG</p><h2 className="mt-2 text-2xl sm:text-3xl font-black tracking-tight">Bagaimana layout Dapur MBG seharusnya disusun?</h2><p className="mt-4 text-sm leading-6 text-slate-600">Alur kerja dapur dapat disusun dari penerimaan bahan, penyimpanan, persiapan, pengolahan, pemorsian/pengemasan, hingga loading agar setiap area memiliki fungsi yang jelas.</p><div className="mt-5 flex flex-wrap items-center gap-2 text-xs font-bold text-slate-600">{['Penerimaan', 'Penyimpanan', 'Persiapan', 'Pengolahan', 'Pemorsian / Packing', 'Loading'].map((item, index) => <span key={item} className="inline-flex items-center gap-2"><span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5">{item}</span>{index < 5 && <ArrowRight className="w-3 h-3 text-slate-400" />}</span>)}</div></div><div className="rounded-3xl bg-slate-950 p-6 sm:p-8 text-white"><Utensils className="w-8 h-8 text-emerald-400" /><h3 className="mt-5 text-xl font-black">Mulai dari kebutuhan dapurnya.</h3><p className="mt-2 text-sm leading-6 text-slate-400">Kapasitas, kondisi ruang, alur kerja, dan equipment perlu dipertimbangkan sebelum menentukan komposisi dapur.</p><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-emerald-400 hover:text-emerald-300">Konsultasikan Layout <ArrowRight className="w-4 h-4" /></a></div></div></section>
        <section className="max-w-7xl mx-auto px-4 py-10 sm:py-12"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">Peralatan SPPG Sesuai Kebutuhan Operasional</p><h2 className="mt-1 text-lg sm:text-xl font-black">Peralatan SPPG Sesuai Kebutuhan Operasional</h2><p className="mt-2 max-w-3xl text-xs sm:text-sm leading-5 text-slate-600">BGN menyediakan pedoman mengenai kebutuhan peralatan dapur SPPG. Komposisi equipment perlu disesuaikan dengan kapasitas dan kondisi dapur. Pedoman BGN menyebut kebutuhan alat disusun berdasarkan pengalaman dan evaluasi SPPG serta kapasitas layanan.</p></div><a href={BGN_JUKNIS_URL} target="_blank" rel="noopener noreferrer" className="shrink-0 inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-xs font-black text-slate-800 hover:bg-slate-100 transition-colors">Lihat Pedoman BGN <ArrowRight className="w-3.5 h-3.5" /></a></div></div></section>
        <section className="max-w-7xl mx-auto px-4 py-12 sm:py-16"><div className="rounded-3xl bg-slate-900 p-6 sm:p-8 lg:p-10 text-white grid lg:grid-cols-[1fr_auto] gap-8 items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-400">Paket Dapur MBG</p><h2 className="mt-2 text-2xl sm:text-3xl font-black tracking-tight">Paket Hemat Peralatan Dapur MBG</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">BBKitchen menyediakan opsi paket equipment untuk kebutuhan Dapur MBG. Detail equipment, jumlah, ukuran, dan kebutuhan instalasi tersedia dalam katalog.</p><p className="mt-4 text-xs text-slate-400">Katalog mencantumkan harga Rp250 juta per 1 September 2025. Harga dapat berubah sebelum kontrak.</p></div><div className="flex flex-col sm:flex-row lg:flex-col gap-3 lg:min-w-[230px]"><a href={CATALOG_PDF_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-900 hover:bg-slate-100 transition-colors"><FileText className="w-4 h-4" />Lihat Katalog Paket</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-5 py-3 text-sm font-black text-white hover:bg-slate-800 transition-colors">Konsultasi Paket <ArrowRight className="w-4 h-4" /></a></div></div></section>
        <section className="max-w-7xl mx-auto px-4 py-14 sm:py-20 text-center"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Konsultasi Dapur MBG</p><h2 className="mt-2 text-3xl sm:text-4xl font-black tracking-tight">Sedang menyiapkan Dapur MBG atau SPPG?</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-500">Konsultasikan kebutuhan equipment, kapasitas, dan layout dapur Anda dengan BBKitchen.</p><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 text-sm font-black text-white hover:bg-emerald-500 transition-colors">Konsultasi via WhatsApp <ArrowRight className="w-4 h-4" /></a></section>
      </main>
      <Footer onSelectCategory={() => undefined} />
    </div>
  );
}
